java:
  build:
    maven: 
      command: "mvn -Dmaven.test.failure.ignore=true clean package" 
    gradle:
      command: "test"
  unittest:
    junit:
      command: "mvn test"
  codecoverage:
    jacoco:
      command: "mvn clean test"
