java:
  build:
    maven: 
      command: "mvn -Dmaven.test.failure.ignore=true clean package" 
    gradle:
      command: "test"
  unittest:
    junit:
      command: "mvn test"
      surefire: "mvn surefire-report:report-only"         
  codecoverage:
    jacoco:
      command: "mvn clean test"
